apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-backend
  labels:
    app: contact-backend
    {{- include "contact-form-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: contact-backend
  template:
    metadata:
      labels:
        app: contact-backend
    spec:
      containers:
        - name: contact-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: {{ .Values.backend.existingSecret }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}