apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    {{- include "contact-form-app.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.backend.port }}"
  CORS_ORIGIN: {{ .Values.backend.corsOrigin | quote }}