apiVersion: v1
kind: Service
metadata:
  name: contact-backend
  labels:
    {{- include "contact-form-app.labels" . | nindent 4 }}
spec:
  selector:
    app: contact-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}