apiVersion: v1
kind: Service
metadata:
  name: contact-frontend
  labels:
    {{- include "contact-form-app.labels" . | nindent 4 }}
spec:
  selector:
    app: contact-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}