sonar.organization=maxvast
sonar.projectKey=maxvast_contact-form-app
sonar.projectName=Contact Form App
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/reports/**,\
  **/vendor/**,\
  **/*_test.go

sonar.coverage.exclusions=backend/cmd/**/main.go
  
sonar.go.coverage.reportPaths=backend/reports/backend-coverage.out

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info