apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contact-form-ingress
  namespace: contact-form
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: contact.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contact-frontend
                port:
                  number: 8080
