apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: contact-form
type: Opaque
stringData:
  POSTGRES_USER: contact
  POSTGRES_PASSWORD: change-me-in-prod
  POSTGRES_DB: contact_db
