apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: contact-form
spec:
  clusterIP: None   # headless, requis pour un StatefulSet
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
