name: build and test
on:
  pull_request:
    branches:
      - develop
env:
  APP_ENV: test
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Go dependencies
        uses: actions/cache@v5
        env:
          CACHE_NAME: cache-go-modules
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('backend/go.sum') }}

      - name: Cache npm dependencies
        uses: actions/cache@v5
        env:
          CACHE_NAME: cache-npm-modules
        with:
          path: |
            frontend/node_modules
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install docker-compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run App
        run: task install

      - name: Wait for service
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q contact-backend)")"; do
          case $status in
           starting) sleep 1;;
           healthy) exit 0;;
           unhealthy)
             docker-compose ps
             docker-compose logs contact-backend
             exit 1
           ;;
          esac
          done
          exit 1

      - name: Check App
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}\n' 'http://localhost:8080/health')
          if [ "$HTTP_CODE" = "200" ]; then
              exit 0
          fi
          docker-compose logs contact-backend
          exit 1

      - name: Check Database
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}\n' 'http://localhost:8080/ready')
          if [ "$HTTP_CODE" = "200" ]; then
              exit 0
          fi
          docker-compose logs contact-backend
          exit 1

      - name: Run Tests
        run: task ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: reports/
          retention-days: 1

      - name: Stop containers
        if: always()
        run: docker-compose down -v